name: flutter_developer_assessment
description: "Flutter developer assessment project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  infinite_scroll_pagination:
  very_good_infinite_list: ^0.9.0
  get_it: ^8.2.0
  share_plus: ^12.0.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true