// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'local_storage/article_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 899199605212609318),
    name: 'ArticleEntity',
    lastPropertyId: const obx_int.IdUid(6, 5692620570725152372),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7741277497253588508),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3113903716704325308),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3937756565847485062),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3077259184117992351),
        name: 'url',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2218193001182407549),
        name: 'urlToImage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5692620570725152372),
        name: 'publishedAt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 899199605212609318),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ArticleEntity: obx_int.EntityDefinition<ArticleEntity>(
      model: _entities[0],
      toOneRelations: (ArticleEntity object) => [],
      toManyRelations: (ArticleEntity object) => {},
      getId: (ArticleEntity object) => object.id,
      setId: (ArticleEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ArticleEntity object, fb.Builder fbb) {
        final titleOffset = object.title == null
            ? null
            : fbb.writeString(object.title!);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final urlOffset = object.url == null
            ? null
            : fbb.writeString(object.url!);
        final urlToImageOffset = object.urlToImage == null
            ? null
            : fbb.writeString(object.urlToImage!);
        final publishedAtOffset = object.publishedAt == null
            ? null
            : fbb.writeString(object.publishedAt!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, urlOffset);
        fbb.addOffset(4, urlToImageOffset);
        fbb.addOffset(5, publishedAtOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final urlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final urlToImageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final publishedAtParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final object = ArticleEntity(
          id: idParam,
          title: titleParam,
          description: descriptionParam,
          url: urlParam,
          urlToImage: urlToImageParam,
          publishedAt: publishedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ArticleEntity] entity fields to define ObjectBox queries.
class ArticleEntity_ {
  /// See [ArticleEntity.id].
  static final id = obx.QueryIntegerProperty<ArticleEntity>(
    _entities[0].properties[0],
  );

  /// See [ArticleEntity.title].
  static final title = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[1],
  );

  /// See [ArticleEntity.description].
  static final description = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[2],
  );

  /// See [ArticleEntity.url].
  static final url = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[3],
  );

  /// See [ArticleEntity.urlToImage].
  static final urlToImage = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[4],
  );

  /// See [ArticleEntity.publishedAt].
  static final publishedAt = obx.QueryStringProperty<ArticleEntity>(
    _entities[0].properties[5],
  );
}
